-- AlterTable: denormalized service rating aggregates
ALTER TABLE "services" ADD COLUMN     "ratingAvg" DECIMAL(3,2),
ADD COLUMN     "reviewCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable: struck-through list price for variants
ALTER TABLE "service_variants" ADD COLUMN     "originalPrice" DECIMAL(12,2);

-- NOTE: Prisma's autogenerated diff wanted to DROP the composite same-service
-- FKs/indexes on package_items because its schema language can't model composite
-- FKs. Those are intentional DB-level invariants from the catalog_refactor
-- migration, so the generated DROP statements were removed here.
--
-- The DROP ... IF EXISTS before each ADD makes this idempotent across both
-- histories: on this dev DB the failed first apply had dropped the FKs (so they
-- are re-created), while on a fresh DB catalog_refactor already created them (so
-- they are dropped-then-recreated). Either way replay/`migrate deploy` is safe.
-- The supporting UNIQUE indexes survive and are reused.
ALTER TABLE "package_items" DROP CONSTRAINT IF EXISTS "package_items_variant_same_service_fk";
ALTER TABLE "package_items"
  ADD CONSTRAINT "package_items_variant_same_service_fk"
  FOREIGN KEY ("serviceVariantId", "serviceId") REFERENCES "service_variants"("id", "serviceId");
ALTER TABLE "package_items" DROP CONSTRAINT IF EXISTS "package_items_package_same_service_fk";
ALTER TABLE "package_items"
  ADD CONSTRAINT "package_items_package_same_service_fk"
  FOREIGN KEY ("packageId", "serviceId") REFERENCES "packages"("id", "serviceId");
